CREATE TABLE IF NOT EXISTS admins (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('super_admin', 'admin')),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  bio TEXT DEFAULT '',
  photo_url TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_requests (
  id SERIAL PRIMARY KEY,
  admin_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
  phone VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
  id SERIAL PRIMARY KEY,
  admin_id INTEGER REFERENCES admins(id) ON DELETE SET NULL,
  application_name VARCHAR(255) NOT NULL DEFAULT 'ProfileTrackHub',
  company_name VARCHAR(255) NOT NULL DEFAULT 'ProfileTrackHub',
  logo_url TEXT,
  job_title VARCHAR(255) NOT NULL,
  job_role VARCHAR(255) NOT NULL DEFAULT 'General',
  location VARCHAR(255) DEFAULT '',
  salary VARCHAR(255) DEFAULT '',
  job_type VARCHAR(100) DEFAULT '',
  vacancies INTEGER NOT NULL DEFAULT 1,
  skills TEXT,
  experience VARCHAR(255),
  job_description TEXT,
  public_slug VARCHAR(255) UNIQUE,
  public_token VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_roles (
  id SERIAL PRIMARY KEY,
  role_name VARCHAR(255) NOT NULL UNIQUE,
  created_by INTEGER REFERENCES admins(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE candidates
ADD COLUMN IF NOT EXISTS full_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
ADD COLUMN IF NOT EXISTS preferred_role VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS source VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS hybrid TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS relocate VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS resume_url TEXT,
ADD COLUMN IF NOT EXISTS extra_file TEXT,
ADD COLUMN IF NOT EXISTS job_id INTEGER,
ADD COLUMN IF NOT EXISTS admin_id INTEGER,
ADD COLUMN IF NOT EXISTS job_title VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS job_role VARCHAR(255) DEFAULT 'General',
ADD COLUMN IF NOT EXISTS job_description TEXT,
ADD COLUMN IF NOT EXISTS job_location VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS work_preference TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS contract_type VARCHAR(100) DEFAULT '',
ADD COLUMN IF NOT EXISTS visa VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS linkedin_url TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS skills TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS experience VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'New',
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
