CREATE TABLE IF NOT EXISTS admins (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('super_admin', 'admin')),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  bio TEXT DEFAULT '',
  photo_url TEXT DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_requests (
  id SERIAL PRIMARY KEY,
  admin_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
  phone VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS help_requests (
  id SERIAL PRIMARY KEY,
  admin_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
  request_type VARCHAR(40) NOT NULL DEFAULT 'Query',
  requester_name VARCHAR(255) NOT NULL DEFAULT '',
  contact_info VARCHAR(255) NOT NULL DEFAULT '',
  subject VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'New',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
  id SERIAL PRIMARY KEY,
  admin_id INTEGER REFERENCES admins(id) ON DELETE SET NULL,
  application_name VARCHAR(255) NOT NULL DEFAULT 'ProfileTrackHub',
  company_name VARCHAR(255) NOT NULL DEFAULT 'ProfileTrackHub',
  logo_url TEXT,
  job_title VARCHAR(255) NOT NULL,
  job_role VARCHAR(255) NOT NULL DEFAULT 'General',
  location VARCHAR(255) DEFAULT '',
  salary VARCHAR(255) DEFAULT '',
  job_type VARCHAR(100) DEFAULT '',
  vacancies INTEGER NOT NULL DEFAULT 1,
  skills TEXT,
  experience VARCHAR(255),
  job_description TEXT,
  public_slug VARCHAR(255) UNIQUE,
  public_token VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_roles (
  id SERIAL PRIMARY KEY,
  role_name VARCHAR(255) NOT NULL UNIQUE,
  created_by INTEGER REFERENCES admins(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS candidates (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(50),
  preferred_role VARCHAR(255) DEFAULT '',
  source VARCHAR(255) DEFAULT '',
  hybrid TEXT DEFAULT '',
  relocate VARCHAR(255) DEFAULT '',
  resume_url TEXT,
  resume_preview_url TEXT,
  extra_file TEXT,
  job_id INTEGER,
  admin_id INTEGER,
  job_title VARCHAR(255) DEFAULT '',
  job_role VARCHAR(255) DEFAULT 'General',
  job_description TEXT,
  job_location VARCHAR(255) DEFAULT '',
  work_preference TEXT DEFAULT '',
  contract_type VARCHAR(100) DEFAULT '',
  visa VARCHAR(255) DEFAULT '',
  linkedin_url TEXT DEFAULT '',
  skills TEXT DEFAULT '',
  experience VARCHAR(255) DEFAULT '',
  location VARCHAR(255) DEFAULT '',
  status VARCHAR(50) DEFAULT 'New',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ads (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL,
  link_url TEXT DEFAULT '',
  target_page VARCHAR(40) NOT NULL DEFAULT 'both',
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by INTEGER REFERENCES admins(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
  role_scope VARCHAR(20) NOT NULL DEFAULT 'ADMIN',
  actor_id INTEGER REFERENCES admins(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(60) NOT NULL DEFAULT 'SYSTEM',
  entity_type VARCHAR(60) NOT NULL DEFAULT 'system',
  entity_id INTEGER,
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE help_requests
DROP CONSTRAINT IF EXISTS help_requests_status_check;

ALTER TABLE help_requests
ADD COLUMN IF NOT EXISTS admin_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS request_type VARCHAR(40) NOT NULL DEFAULT 'Query',
ADD COLUMN IF NOT EXISTS requester_name VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS contact_info VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS subject VARCHAR(255) NOT NULL DEFAULT 'Support request',
ADD COLUMN IF NOT EXISTS message TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'New',
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE help_requests
ADD CONSTRAINT help_requests_status_check
CHECK (status IN ('New', 'In Review', 'Resolved'));

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS admin_id INTEGER REFERENCES admins(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS company_name VARCHAR(255) NOT NULL DEFAULT 'ProfileTrackHub',
ADD COLUMN IF NOT EXISTS public_slug VARCHAR(255),
ADD COLUMN IF NOT EXISTS public_token VARCHAR(255),
ADD COLUMN IF NOT EXISTS application_name VARCHAR(255) NOT NULL DEFAULT 'ProfileTrackHub',
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS job_role VARCHAR(255) NOT NULL DEFAULT 'General',
ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS salary VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS job_type VARCHAR(100) DEFAULT '';

ALTER TABLE candidates
ADD COLUMN IF NOT EXISTS full_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
ADD COLUMN IF NOT EXISTS preferred_role VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS source VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS hybrid TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS relocate VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS resume_url TEXT,
ADD COLUMN IF NOT EXISTS resume_preview_url TEXT,
ADD COLUMN IF NOT EXISTS extra_file TEXT,
ADD COLUMN IF NOT EXISTS job_id INTEGER,
ADD COLUMN IF NOT EXISTS admin_id INTEGER,
ADD COLUMN IF NOT EXISTS job_title VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS job_role VARCHAR(255) DEFAULT 'General',
ADD COLUMN IF NOT EXISTS job_description TEXT,
ADD COLUMN IF NOT EXISTS job_location VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS work_preference TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS contract_type VARCHAR(100) DEFAULT '',
ADD COLUMN IF NOT EXISTS visa VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS linkedin_url TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS skills TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS experience VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'New',
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS role_scope VARCHAR(20) NOT NULL DEFAULT 'ADMIN',
ADD COLUMN IF NOT EXISTS actor_id INTEGER REFERENCES admins(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL DEFAULT 'Notification',
ADD COLUMN IF NOT EXISTS message TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS type VARCHAR(60) NOT NULL DEFAULT 'SYSTEM',
ADD COLUMN IF NOT EXISTS entity_type VARCHAR(60) NOT NULL DEFAULT 'system',
ADD COLUMN IF NOT EXISTS entity_id INTEGER,
ADD COLUMN IF NOT EXISTS is_read BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ads
ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS link_url TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS target_page VARCHAR(40) NOT NULL DEFAULT 'both',
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'Active',
ADD COLUMN IF NOT EXISTS start_date DATE,
ADD COLUMN IF NOT EXISTS end_date DATE,
ADD COLUMN IF NOT EXISTS created_by INTEGER REFERENCES admins(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_admin_id ON jobs(admin_id);
CREATE INDEX IF NOT EXISTS idx_jobs_public_slug ON jobs(public_slug);
CREATE INDEX IF NOT EXISTS idx_jobs_job_role ON jobs(job_role);
CREATE INDEX IF NOT EXISTS idx_candidates_job_id ON candidates(job_id);
CREATE INDEX IF NOT EXISTS idx_candidates_admin_id ON candidates(admin_id);
CREATE INDEX IF NOT EXISTS idx_password_requests_status ON password_requests(status);
CREATE INDEX IF NOT EXISTS idx_help_requests_admin_id ON help_requests(admin_id);
CREATE INDEX IF NOT EXISTS idx_help_requests_created_at ON help_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_roles_role_name ON job_roles(role_name);
CREATE INDEX IF NOT EXISTS idx_ads_status_target_dates ON ads(status, target_page, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);
